### ISSUE TITLE
error in line 86 of Trainer.py 

### ISSUE THREAD

**Issue by xukai504087493** [MattKleinsmith/pbt#1]
error in line 86 of Trainer.py :
Execute this statement:
with torch.no_grad ():
AttributeError: 'module' object has no attribute 'no_grad',
How to solve this?  Thank you

**Comment by MattKleinsmith** [comment]
**Why it doesn't work:**
torch.no_grad() replaced Variable.volatile in the master branch of PyTorch, and it's not backward compatible.
https://github.com/pytorch/pytorch/pull/3970

**How to fix it now:**
You can modify the code in the following way: delete `with torch.no_grad():` and unindent the block under it and things should run. To preserve the speed increase from no_grad, add `volatile=True` in each Variable call. Another option: [install PyTorch from source](https://github.com/pytorch/pytorch#from-source) to get the pre-release, however I'd advise against that; see below.

**I'll fix it soon:**
I'll downgrade the PyTorch used in this repo to the easily installable version later and make the code changes I mentioned above.

**Comment by xukai504087493** [comment]
Seems this works when I delete "with torch.no_grad()".
Could you offer the Figures plot code? How do you plot the four figuer? Thank you so much.

**Comment by MattKleinsmith** [comment]
Fixed via https://github.com/MattKleinsmith/pbt/commit/855ac3bac9032d26b207e71d47ca6e4615b62cc3: `Replace no_grad() with volatile to allow PyTorch 0.3.0`

---

> Could you offer the Figures plot code? How do you plot the four figuer?

I'll scavenge my old code and re-add logging and plotting.
